.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FPF" "5" "February 2012" "" "FPF"
.
.SH "NAME"
\fBfpf\fR \- effing package format
.
.SH "SYNOPSIS"
.
.SH "DESCRIPTION"
.
.SH "THEME SONG"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
Part of \fBfpf\fR(1)\.
