.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FPF\-REMOVE" "1" "February 2012" "" "FPF"
.
.SH "NAME"
\fBfpf\-remove\fR \- remove an installed FPF package
.
.SH "SYNOPSIS"
\fBfpf\-remove\fR [\fB\-\-deps\fR] [\fB\-\-prefix\fR=\fIprefix\fR] \fIname\fR
.
.SH "DESCRIPTION"
\fBfpf\-remove\fR removes the installed files and metadata for \fIname\fR from \fIprefix\fR\.
.
.P
By default, \fBfpf\-remove\fR does not invoke \fBfpf\-rollback\-deps\fR(1)\. This behavior can be enabled with \fB\-\-deps\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-deps\fR
Remove dependencies\.
.
.TP
\fB\-\-prefix\fR=\fIprefix\fR
The installation prefix\.
.
.SH "THEME SONG"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
Part of \fBfpf\fR(1)\.
